#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])

# This is the path to Windows SDK libraries, specifically WindowsApp.lib, which contains the Speech Synthesis API.
# Update this folder to point to your Windows SDK instalation like that
# [PROGRAM_FILES_X86]/Windows Kits/[Windows SDK Major Version]/Lib/[Windows SDK ]
env.Append(LIBPATH=["C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64"])
env.Append(LIBS=['WindowsApp'])

sources = [Glob("src/*.cpp")]

library = env.SharedLibrary(
    "../addons/winrt-speech-synthesis/winrt_speech_synthesis{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
