#!/usr/bin/env python
import subprocess
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])

# Referenced WinRT libraries
env.Append(LIBS=[
    'runtimeobject',
    'ole32',
    'oleaut32',
])

sources = [Glob("src/*.cpp")]

library = env.SharedLibrary(
    "../addons/winrt-speech-synthesis/winrt_speech_synthesis{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
